### PR TITLE
Adding support for Datacite searching

### PR DESCRIPTION
**Pull request by arfon**
Fixes https://github.com/arfon/metamatter/issues/4

/ cc @mfenner incase you're interested.

### CODE REVIEW

**Comment by mfenner** [comment]
I think you will sometimes see multiple DOIs for one Github URL, because a new release will probably create a new DOI.

**Comment by arfon** [comment]
Yeah, I'm not sure what to do about this. I was thinking of just warning the user when generating the output and let them make a decision?

**Comment by mfenner** [comment]
Is showing multiple DOIs an option? Ideally you would also show the relations (e.g. `IsNewVersionOf`), but that might be too much effort.

**Comment by arfon** [comment]
For this first pass I think I'm going to just return something like this in the output from the gem:

```
Warning: More than one DOI from Datacite search returned
Search string: http://search.datacite.org/api?q=relatedIdentifier:https://github.com/articlemetrics/lagotto&fl=doi,creator,title,publisher,publicationYear,resourceTypeGeneral,datacentre,datacentre_symbol,prefix,relatedIdentifier&fq=is_active:true&fq=has_metadata:true&rows=1000&wt=json
- 10.5281/ZENODO.20039
- 10.5281/ZENODO.20050
```

**Comment by mfenner** [comment]
Your example is interesting, as it returns not only the DOI associated with the Github repo, but also the DOI of a dataset that was generated with the software and is therefore linked in the metadata. Maybe you have to also check `ResourceTypeGeneral`, but this is probably still an edge case.

**Comment by arfon** [comment]
So hitting up [this URL](http://search.datacite.org/api?q=relatedIdentifier:https://github.com/articlemetrics/lagotto&fl=doi,creator,title,publisher,publicationYear,resourceTypeGeneral,datacentre,datacentre_symbol,prefix,relatedIdentifier&fq=is_active:true&fq=has_metadata:true&rows=1000&wt=json) returns me this response.

```
{
    "response": {
        "docs": [
            {
                "creator": [
                    "Public Library of Science"
                ],
                "datacentre": "CERN.ZENODO - ZENODO - Research. Shared.",
                "datacentre_symbol": "CERN.ZENODO",
                "doi": "10.5281/ZENODO.20039",
                "prefix": "10.5281",
                "publicationYear": "2015",
                "publisher": "Zenodo",
                "relatedIdentifier": [
                    "IsSupplementTo:URL:https://github.com/articlemetrics/lagotto",
                    "IsSupplementTo:DOI:10.3789/isqv25no2.2013.04",
                    "HasPart:URL:https://zenodo.org/record/20039/files/alm_report_2015-07-13.zip"
                ],
                "resourceTypeGeneral": "Dataset",
                "title": [
                    "Cumulative PLOS ALM Report - July 2015"
                ]
            }
        ],
        "numFound": 1,
        "start": 0
    },
    "responseHeader": {
        "QTime": 1,
        "status": 0
    }
}

```

I would have expected the entry (10.5281/ZENODO.20046) for the `altmetrics/lagotto` Zenodo entry to be in this response too right?

**Comment by mfenner** [comment]
The problem is that we had to use `IsSupplementTo` to describe the dataset - software relation. The latest Zenodo release also allows the more appropriate `IsCompiledBy`: https://github.com/zenodo/zenodo/issues/354

This will make it easier to find the Github repo/corresponding Zenodo DOI relationship instead of other relations.

And yes, the relation to `10.5281/ZENODO.20046` should also be there, but the DOI was created after this record. I will update the Ruby code that created this Zenodo record.

**Comment by arfon** [comment]
OK thanks for the extra context @mfenner. Seems like this is a good first pass. Later improvements could do smarter things with the different relationship types. Sound good?

**Comment by mfenner** [comment]
Cool.

**Comment by arfon** [comment]
Thanks for all of your feedback @mfenner

**Pull request merged**
